#pragma kernel CSMain

#include "function.hlsl"
#include "colors.hlsl"
#include "bxdf.hlsl"
#include "test.hlsl"
#include "trace.hlsl"

float3 Shade(Ray ray)
{
    float3 throughput = 1.0;
    float3 L          = 0.0;

    for (int bounce = 0; bounce < _TraceDepth; ++bounce)
    {
        RayHit hit = Trace(ray);
        if (hit.distance >= 1.#INF)
        {
            L += throughput * SampleSkybox(ray);
            break;
        }
        if (hit.material.emissionIntensity > 0.0f)
        {
            L += throughput * (hit.material.emission * hit.material.emissionIntensity);
            break;
        }

        ray.dir = -ray.dir;
        float roulette = RNG_Next(rng);
        
        float3 Lo_direct = GetLightContribution(hit);
        L += throughput * Lo_direct;
        
        if (hit.mode >= 3.0)
        {
            float outside = dot(ray.dir, hit.normal);
            hit.normal *= sign(outside);    // Ensure normal points in the right direction
            // dielectric workflow
            float alpha = SmoothnessToPhongAlpha(hit.material.roughness);
            hit.normal = normalize(lerp(
                hit.normal,
                SampleReflectionDirectionSphere(hit.normal,alpha),
                hit.material.roughness * hit.material.roughness
            ));
            float3 rayOutDir = normalize(reflect(ray.dir, hit.normal));
            float3 H = normalize(ray.dir + rayOutDir);
            float fresnel = DielectricFresnel(dot(H, ray.dir), hit.material.ior);
            float reflChance = 1.0 - (1.0 - fresnel) * (1.0 - hit.material.metallic);
            if (roulette < reflChance)
            {
                float3 brdfCos;
                float  microPdf;
                SpecReflModel(hit, ray.dir, rayOutDir, H, brdfCos, microPdf);
                float pdf = reflChance * microPdf;
                ray.dir = rayOutDir;
                throughput *= brdfCos / pdf;
                L *= reflChance;
            }
            else
            {
                rayOutDir = normalize(refract(ray.dir, -hit.normal, 1.0 / hit.material.ior));
                SpecRefrModel(hit, ray.dir, rayOutDir, H, throughput);
                ray.dir = rayOutDir;
                throughput *= 1.0 / clamp((1.0 - reflChance), 1e-2, 1.0);
                L *= (1.0 - reflChance);
            }
        }
        else
        {
            // Calculate chances of diffuse and specular reflection
            float diffChance = dot(hit.material.albedo, LUM) * (1.0 - hit.material.metallic);
            if(roulette > diffChance)
            {
                float3 rayOutDir = normalize(lerp(
                    reflect(ray.dir,hit.normal),
                    SampleHemisphere(hit.normal),
                    hit.material.roughness * hit.material.roughness
                    ));

                float3 V = ray.dir;
                float3 LOUT = rayOutDir;
                float3 H = normalize(V + LOUT);
                float3 f_brdf;
                float specPdf;
    
                SpecReflModel(hit, V, LOUT, H, f_brdf, specPdf);
    
                float NdotL = saturate(dot(hit.normal, LOUT));
                float branchPdf = (1.0 - diffChance);
                float totalPdf = specPdf * branchPdf;
    
                throughput *= f_brdf * NdotL / max(totalPdf, 1e-4);
                ray.dir = rayOutDir;
                L *= hit.material.roughness * hit.material.roughness;
            }
            else{
                float3 rayOutDir = normalize(SampleHemisphere(hit.normal));

                // Diffuse Model
                float NdotL = saturate(dot(hit.normal, rayOutDir));
                float diffusePdf = NdotL / PI; // cosine-weighted hemisphere sampling
                float branchPdf = diffChance;
                float totalPdf = diffusePdf * branchPdf;
    
                float3 diffuseAlbedo = hit.material.albedo * (1.0 - hit.material.metallic);
                float3 f_diffuse = diffuseAlbedo / PI;
    
                throughput *= f_diffuse * NdotL / max(totalPdf, 1e-4);
    
                ray.dir = rayOutDir;
            }
        }

        float p = max(throughput.r, max(throughput.g, throughput.b));
        if (RNG_Next(rng) >= p)
            break;
        throughput *= 1.0 / p;
        ray.invDir = 1.0 / ray.dir;
        ray.origin = hit.position + hit.normal * 1e-5;
    }
    return L;
}

[numthreads(8,8,1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    RNG_SeedPixel(rng, id.xy, _FrameCount);
    Ray r = GenRayByID(id.xy);
    _Pixel = id.xy;
    
    if (_OnlyDrawAlbedo || _OnlyDrawDepth || _OnlyDrawNormals)
    {
        RayHit firstHit = Trace(r);

        if (_OnlyDrawAlbedo)
            _Result[id.xy] = float4(firstHit.material.albedo, 1.0f);

        else if (_OnlyDrawDepth)
        {
            float nd = firstHit.distance / _CameraFar;
            _Result[id.xy] = float4(nd, nd, nd, 1.0f);
        }
        else if (_OnlyDrawNormals)
            _Result[id.xy] = float4(firstHit.normal * 0.5f + 0.5f, 1.0f);

        return;
    }

    float3 L = Shade(r);
    _Result[id.xy] = float4(L, 1.0f);
}

