#pragma kernel CSMain

#include "function.hlsl"
#include "colors.hlsl"
#include "bxdf.hlsl"
#include "test.hlsl"
#include "trace.hlsl"

float3 Shade(inout Ray ray, inout RayHit hit)
{
    if(hit.distance < 1.#INF)
    {
        // if (dot(hit.material.emission, float3(1.0, 1.0, 1.0)) > 0.0) {
        //     ray.energy = 0;
        //     hit.should_break = true;
        //     return hit.material.emission;
        // }
        
        float3 lightContribution = GetLightContribution(hit);

        float roulette = RNG_Next(rng);
        if (hit.mode >= 3.0)
        {
            float outside = dot(ray.dir, hit.normal);
            hit.normal *= sign(outside);    // Ensure normal points in the right direction
            ray.origin = hit.position + hit.normal * 1e-5;
            // dielectric workflow
            float alpha = SmoothnessToPhongAlpha(hit.material.roughness);
            hit.normal = normalize(lerp(
                hit.normal,
                SampleReflectionDirectionSphere(hit.normal,alpha),
                hit.material.roughness * hit.material.roughness
            ));
            float3 rayOutDir = normalize(reflect(ray.dir, hit.normal));
            float3 H = normalize(ray.dir + rayOutDir);
            float fresnel = DielectricFresnel(dot(H, ray.dir), hit.material.ior);
            float reflChance = 1.0 - (1.0 - fresnel) * (1.0 - hit.material.metallic);
            if (roulette < reflChance)
            {
                //rayOutDir = normalize(reflect(-ray.dir, H));
                SpecReflModel(hit, ray.dir, rayOutDir, H, ray.energy);
                ray.dir = rayOutDir;
                ray.energy *= 1.0 / clamp(reflChance, 1e-2, 1.0);
                lightContribution *= reflChance;
            }
            else
            {
                rayOutDir = normalize(refract(ray.dir, -hit.normal, 1.0 / hit.material.ior));
                SpecRefrModel(hit, ray.dir, rayOutDir, H, ray.energy);
                ray.dir = rayOutDir;
                ray.energy *= 1.0 / clamp((1.0 - reflChance), 1e-2, 1.0);
                lightContribution *= (1.0 - reflChance);
            }
        }

        else
        {
            // Calculate chances of diffuse and specular reflection
            float diffChance = dot(hit.material.albedo, LUM) * (1.0 - hit.material.metallic);
            
            ray.origin = hit.position + hit.normal * 1e-5; // Offset the origin slightly to avoid self-intersection
            if(roulette > diffChance)
            {
                float alpha = SmoothnessToPhongAlpha(hit.material.roughness);
                float3 rayOutDir = normalize(lerp(
                    reflect(ray.dir,hit.normal),
                    // SampleReflectionDirectionSphere(hit.normal, alpha),
                    SampleHemisphere4(hit.normal),
                    hit.material.roughness * hit.material.roughness
                    ));

                // Specular Model
                float3 H = normalize(rayOutDir + ray.dir);  // Half vector
                float NdotL = abs(dot(hit.normal, ray.dir));
                float specColor = lerp(0.04, hit.material.albedo, hit.material.metallic);
                float3 F = SchlickFresnel(dot(rayOutDir, H),specColor);
                float G = SmithG(NdotL, hit.material.roughness);
                ray.energy *= F * G;

                ray.dir = rayOutDir;
                ray.energy *= 1.0 / clamp(1.0 - diffChance, 1e-2, 1.0);
                lightContribution *= hit.material.roughness * hit.material.roughness;
            }
            else{
                float3 rayOutDir = normalize(SampleHemisphere4(hit.normal));
                float3 H = normalize(rayOutDir + ray.dir);  // Half vector

                // Diffuse Model
                float NdotL = saturate(dot(hit.normal, rayOutDir));
                float NdotV = saturate(dot(hit.normal, ray.dir));
                float fd90 = 0.5 + 2.0 * hit.material.roughness * dot(rayOutDir, H) * dot(rayOutDir, H);
                float fd = lerp(1.0, fd90, NdotL) * lerp(1.0, fd90, NdotV);
                ray.energy *= (1.0 - hit.material.metallic) * fd * hit.material.albedo;

                ray.dir = rayOutDir;
                ray.energy *= 1.0 / clamp(diffChance, 1e-2, 1.0);
            }
        }
        // hit.should_break = hit.material.emission >= 0.0;
        return hit.material.emission + lightContribution;
    }
    else
    {
        ray.energy = 0.0f;
        return SampleSkybox(ray);
    }
}

[numthreads(8,8,1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    RNG_SeedPixel(rng, id.xy, _FrameCount);
    Ray r = GenRayByID(id.xy);
    _Pixel = id.xy;
    float3 result = float3(0.0f, 0.0f, 0.0f);

    
    for(int i = 0; i < _TraceDepth; i++)
    {
        RayHit hit = Trace(r);

        _Result[id.xy] = IntersectTlasFast(r, 1.#INF);
        
        if (_OnlyDrawAlbedo)
        {
            _Result[id.xy] = float4(hit.material.albedo, 1.0f);
            return;
        }
        // if (_OnlyDrawDepth)
        // {
        //     hit.distance = hit.distance / _CameraFar;
        //     _Result[id.xy] = float4(hit.distance, hit.distance, hit.distance, 1.0f);
        //     return;
        // }
        if (_OnlyDrawNormals)
        {
            _Result[id.xy] = float4(hit.normal * 0.5f + 0.5f, 1.0f);
            return;
        }

        if (_OnlyDrawDepth)
        {
            hit.distance = hit.distance / _CameraFar;
            result += float4(hit.distance, hit.distance, hit.distance, 1.0f);
            continue;
        }
        
        result += r.energy * SRGB2Linear(Shade(r, hit));
        
        if (!any(r.energy))
        {
            break;
        }
    }
    // _Result[id.xy] = float4(result, 1.0f);
}

